lib/storex_web/router.ex
defmodule StorexWeb.Router do
  use StorexWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug StorexWeb.Plugs.Cart
    plug StorexWeb.Plugs.ItemsCount
    plug StorexWeb.Plugs.CurrentUser
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", StorexWeb do
    # Use the default browser stack
    pipe_through :browser

    get "/", BookController, :index
    resources "/books", BookController

    resources "/cart", CartController,
      singleton: true,
      only: [:show, :create, :delete]

    resources "/checkout", CheckoutController, only: [:new, :create]

    resources "/session", SessionController,
      only: [:new, :create],
      singleton: true

    resources "/users", UserController, only: [:new, :create]
  end

  # Other scopes may use custom stacks.
  # scope "/api", StorexWeb do
  #   pipe_through :api
  # end
end

lib/storex_web/controllers/checkout_controller.ex
defmodule StorexWeb.CheckoutController do
  use StorexWeb, :controller
  alias Storex.Sales
  alias StorexWeb.Plugs
  alias Plugs.Cart, as: SessionCart
  alias Plugs.CurrentUser

  plug :ensure_current_user

  def new(conn, _params) do
    changeset = Sales.new_order()

    conn
    |> with_cart_information()
    |> render("new.html", changeset: changeset)
  end

  def create(conn, %{"order" => order_params}) do
    cart = SessionCart.get(conn)
    user = CurrentUser.get(conn)

    case Sales.process_order(user, cart, order_params) do
      {:ok, _order} ->
        conn
        |> put_flash(:info, "Order successfuly created. Thanks!")
        |> SessionCart.forget()
        |> redirect(to: book_path(conn, :index))

      {:error, changeset} ->
        conn
        |> with_cart_information()
        |> render("new.html", changeset: changeset)
    end
  end

  defp ensure_current_user(conn, _opts) do
    if CurrentUser.get(conn) do
      conn
    else
      conn
      |> put_flash(:error, "Sign in or Sign up before you continue")
      |> redirect(to: user_path(conn, :new))
      |> halt()
    end
  end

  defp with_cart_information(conn) do
    items =
      conn
      |> SessionCart.get()
      |> Sales.list_line_items()

    items_count = Sales.line_items_quantity_count(items)
    total_price = Sales.line_items_total_price(items)

    conn
    |> assign(:items_count, items_count)
    |> assign(:total_price, total_price)
  end
end

lib/storex_web/views/checkout_view.ex
defmodule StorexWeb.CheckoutView do
  use StorexWeb, :view
  import StorexWeb.Helpers.PriceFormatter
end

lib/storex_web/templates/checkout/new.html.eex
<h1>Checkout</h1>

<%= form_for @changeset, checkout_path(@conn, :create), fn f -> %>
  <div class="form-group">
    <h2>Order information</h2>

    <dl>
      <dt>Number of items</dt>
      <dd><%= @items_count %></dd>
    </dl>

    <dl>
      <dt>Total price</dt>
      <dd><%= format_price(@total_price) %></dd>
    </dl>
  </div>

  <div class="form-group">
    <h2>Shipping information</h2>

    <div class="form-field">
      <label>Recipient</label>
      <span class="value"><%= @current_user.full_name %></span>
    </div>

    <div class="form-field">
      <%= label(f, :address) %>
      <%= error_tag(f, :address) %>
      <%= text_input(f, :address) %>
    </div>
  </div>

  <%= submit("Buy!", class: "button button-primary") %>
<% end %>